export const GUIDED_LESSONS = {
  "simple-publisher": {
    templateId: "simple-publisher",
    title: "Simple Publisher Walkthrough",
    summary: "Practice how a timer callback maps to code, publish flow, and topic fan-out.",
    practiced: ["publisher setup", "timer callback", "publish path", "topic fan-out"],
    steps: [
      {
        id: "publisher-setup-block",
        eventIndex: 0,
        title: "Find the publisher setup",
        prompt: "Click the code block that creates the publisher and registers the timer callback.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["publisher-setup"],
        focus: {
          codeBlockIds: ["publisher-setup"],
          graphElementIds: ["node:simple_publisher", "topic:my_publisher", "edge:pub:publisher_to_topic"],
          eventIndices: [0],
        },
        hint: "Look inside __init__(). The publisher is created before the timer ever fires.",
        successFeedback: "Yes — this block creates the publisher and the timer.",
        correctionFeedback: "Not quite. Look for the constructor block where create_publisher(...) appears.",
        notice: "This is the setup step that makes the publisher-to-topic connection exist at runtime.",
        explanation: {
          what: "The constructor creates the node, publisher, and timer.",
          why: "ROS needs the publisher and timer objects before any callback can run.",
          concept: "Node setup and publisher creation.",
          mapping: "The __init__ block maps directly to the publisher node and topic relationship in the graph.",
        },
      },
      {
        id: "timer-callback-block",
        eventIndex: 1,
        title: "Find the timer callback",
        prompt: "Click the code block that runs when the timer expires.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["timer-callback"],
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: ["node:simple_publisher"],
          eventIndices: [1],
        },
        hint: "Look for the function that is named in create_timer(..., self.timer_callback).",
        successFeedback: "Correct — this callback is what the timer triggers.",
        correctionFeedback: "Close. Look for the callback function the timer calls, not the constructor.",
        notice: "The timer causes this callback to run before any message can be published.",
        explanation: {
          what: "timer_callback() is the function ROS invokes when the timer period elapses.",
          why: "create_timer(...) registered this callback during setup.",
          concept: "Timer-driven execution.",
          mapping: "The active node in the graph is waiting for the timer, and this callback is the code side of that event.",
        },
      },
      {
        id: "publish-path-graph",
        eventIndex: 3,
        title: "Trace the publish path",
        prompt: "Click the graph path that carries the message from the publisher node into the topic.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:pub:publisher_to_topic"],
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: ["edge:pub:publisher_to_topic", "node:simple_publisher", "topic:my_publisher"],
          eventIndices: [3],
        },
        hint: "It is the first edge the message takes before subscribers see anything.",
        successFeedback: "Yes — that edge represents publish(msg) moving data onto the topic.",
        correctionFeedback: "Not quite. Start at the publisher node and find the first outgoing message path.",
        notice: "A publish call reaches the topic first, then ROS can fan the data out to subscribers.",
        explanation: {
          what: "publish(msg) sends the message from the node into the topic transport.",
          why: "Topics act as the communication channel between publishers and subscribers.",
          concept: "Topic publish flow.",
          mapping: "The publish(msg) line in timer_callback() corresponds to this first graph edge.",
        },
      },
      {
        id: "predict-message-created",
        eventIndex: 1,
        title: "Predict the next step",
        prompt: "After the timer fires, what is the next major step in this example?",
        questionType: "predict_next",
        choices: [
          { id: "message-created", label: "Create and fill a String message" },
          { id: "spin-loop", label: "Return immediately to spin()" },
          { id: "subscriber-update", label: "Subscribers receive the message first" },
        ],
        correctChoiceId: "message-created",
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: ["node:simple_publisher"],
          eventIndices: [1, 2],
        },
        hint: "The callback needs data to publish before the topic can change.",
        successFeedback: "Correct — the callback builds the message before publish(msg) runs.",
        correctionFeedback: "Close. The node prepares the message object before anything moves through the graph.",
        notice: "The code sequence is timer callback, message creation, then publish.",
        explanation: {
          what: "The next step is creating and filling the String message object.",
          why: "ROS cannot publish until the code has prepared a message payload.",
          concept: "Execution order inside a callback.",
          mapping: "In code, msg = String() and msg.data = ... happen before the graph shows any message movement.",
        },
      },
      {
        id: "topic-fan-out",
        eventIndex: 3,
        title: "Find the fan-out point",
        prompt: "Click the graph element that fans the published message out to both subscribers.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["topic:my_publisher"],
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: [
            "topic:my_publisher",
            "edge:pub:topic_to_listener",
            "edge:pub:topic_to_dashboard",
            "node:string_listener",
            "node:string_dashboard",
          ],
          eventIndices: [3],
        },
        hint: "Look for the center channel between the publisher and both subscribers.",
        successFeedback: "Yes — the topic is the shared channel that branches to both subscribers.",
        correctionFeedback: "Not quite. The fan-out happens at the topic itself, not inside either subscriber node.",
        notice: "A single publish call can reach multiple subscribers because the topic is the shared transport.",
        explanation: {
          what: "The topic is the shared communication point that distributes the message to every subscriber.",
          why: "Subscribers listen to the topic rather than to the publisher directly.",
          concept: "Publish/subscribe fan-out.",
          mapping: "One publish(msg) call in code causes the graph to branch from the topic to each subscriber edge.",
        },
      },
    ],
  },
  "symphony-orchestra": {
    templateId: "symphony-orchestra",
    title: "Symphony Orchestra Walkthrough",
    summary: "Practice how a conductor broadcasts cues, why bass skips one stream, how dual-role musicians work, and why this orchestra stays composable.",
    practiced: [
      "broadcast fan-out",
      "selective subscription",
      "dual-role nodes",
      "executor concurrency",
      "fan-out",
      "composability",
      "why multiple nodes",
    ],
    steps: [
      {
        id: "symphony-difference",
        eventIndex: 0,
        title: "How is this different from Simple Publisher?",
        prompt: "Compared with Simple Publisher, what is the biggest new idea in Symphony Orchestra?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "conductor-broadcast",
            label: "A conductor broadcasts cue topics while the musicians both subscribe and publish their own streams",
          },
          {
            id: "single-path",
            label: "One timer still drives one straight publish path with no new subscriber roles",
          },
          {
            id: "service-example",
            label: "The example mainly teaches services instead of topic communication",
          },
        ],
        correctChoiceId: "conductor-broadcast",
        focus: {
          codeBlockIds: ["conductor", "violin", "cello", "bass", "audience", "spotlight", "main-spin"],
          graphElementIds: [
            "node:conductor",
            "topic:tempo",
            "topic:dynamics",
            "node:violin",
            "topic:violin",
            "node:cello",
            "topic:cello",
            "node:bass",
            "topic:bass",
            "node:audience",
            "node:spotlight",
          ],
          eventIndices: [0, 1, 2, 3, 4, 10],
        },
        hint: "Look for the new conductor node and for musician blocks that both subscribe and publish.",
        successFeedback: "Correct — Symphony now teaches a broadcasting conductor, dual-role musicians, and selective listeners in one example.",
        correctionFeedback: "Not quite. The key change is that one node broadcasts cues while the musician nodes both listen and publish.",
        notice: "This version is about distributed roles: one cue source, multiple musician subscriptions, and separate listener paths.",
        explanation: {
          what: "Symphony now has a conductor, dual-role musician nodes, and separate listener nodes.",
          why: "That richer structure makes broadcast cues, selective wiring, and concurrency visible at the same time.",
          concept: "ROS examples become more realistic when nodes both consume and produce data.",
          mapping: "The conductor, musician, audience, and spotlight code blocks line up directly with the separate graph nodes and topic paths.",
        },
      },
      {
        id: "symphony-tempo-broadcast",
        eventIndex: 2,
        title: "Who receives /tempo?",
        prompt: "The conductor just published on /tempo. Which nodes receive that cue?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "all-three-instruments",
            label: "Violin, cello, and bass all receive /tempo",
          },
          {
            id: "violin-cello-only",
            label: "Only violin and cello receive /tempo",
          },
          {
            id: "listeners-only",
            label: "Audience and spotlight receive /tempo directly from the conductor",
          },
        ],
        correctChoiceId: "all-three-instruments",
        focus: {
          codeBlockIds: ["conductor", "violin", "cello", "bass"],
          graphElementIds: [
            "topic:tempo",
            "node:violin",
            "node:cello",
            "node:bass",
            "edge:sym:tempo_to_violin",
            "edge:sym:tempo_to_cello",
            "edge:sym:tempo_to_bass",
          ],
          eventIndices: [1, 2],
        },
        hint: "Look for every node that created a subscription to /tempo.",
        successFeedback: "Correct — /tempo broadcasts to all three instruments.",
        correctionFeedback: "Not quite. Bass follows tempo too, so all three instruments are wired to /tempo.",
        notice: "One topic can wake multiple subscribers at once when they all listen to that channel.",
        explanation: {
          what: "Violin, cello, and bass all receive the /tempo cue.",
          why: "Each musician created a /tempo subscription during setup.",
          concept: "Broadcast fan-out from one published topic to many subscribers.",
          mapping: "The conductor's tempo publish lines map to three outgoing /tempo edges in the graph, one to each instrument.",
        },
      },
      {
        id: "symphony-bass-selective",
        eventIndex: 3,
        title: "Why does bass skip /dynamics?",
        prompt: "The conductor also published /dynamics. Why doesn't bass receive that cue?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "tempo-only",
            label: "Bass only subscribed to /tempo, so ROS never routes /dynamics into that node",
          },
          {
            id: "queue-too-small",
            label: "Bass is subscribed, but the queue size is too small to deliver the message",
          },
          {
            id: "audience-blocks",
            label: "Audience consumes the /dynamics message before bass can see it",
          },
        ],
        correctChoiceId: "tempo-only",
        focus: {
          codeBlockIds: ["conductor", "bass", "violin", "cello"],
          graphElementIds: [
            "topic:dynamics",
            "node:violin",
            "node:cello",
            "node:bass",
            "edge:sym:dynamics_to_violin",
            "edge:sym:dynamics_to_cello",
          ],
          eventIndices: [1, 3],
        },
        hint: "Compare the bass setup block to violin and cello.",
        successFeedback: "Correct — bass deliberately follows /tempo only.",
        correctionFeedback: "Not quite. The teaching point is the missing subscription, not queue size or message stealing.",
        notice: "Selective subscription is visible both in the code and in the missing edge in the graph.",
        explanation: {
          what: "Bass ignores /dynamics because it never subscribed to that topic.",
          why: "The Bass block creates one subscription for /tempo only, while violin and cello create two subscriptions.",
          concept: "Nodes only wake for the topics they explicitly choose to follow.",
          mapping: "The missing edge from /dynamics to bass mirrors the missing create_subscription(..., \"/dynamics\", ...) line in the Bass block.",
        },
      },
      {
        id: "symphony-dual-role",
        eventIndex: 4,
        title: "Find a dual-role musician",
        prompt: "Click one code block that shows a musician both subscribing to conductor cues and publishing its own stream.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["violin", "cello"],
        focus: {
          codeBlockIds: ["violin", "cello"],
          graphElementIds: [
            "node:violin",
            "topic:violin",
            "edge:sym:tempo_to_violin",
            "edge:sym:dynamics_to_violin",
            "edge:sym:violin_to_topic",
            "node:cello",
            "topic:cello",
            "edge:sym:tempo_to_cello",
            "edge:sym:dynamics_to_cello",
            "edge:sym:cello_to_topic",
          ],
          eventIndices: [2, 3, 4, 7],
        },
        hint: "Look for one musician block that contains both create_subscription(...) and create_publisher(...).",
        successFeedback: "Correct — that musician both listens to the conductor and publishes its own instrument stream.",
        correctionFeedback: "Not quite. Pick one of the musician blocks that contains both subscription lines and a publisher.",
        notice: "Most real ROS nodes are dual-role: they consume some data and publish something new in response or in parallel.",
        explanation: {
          what: "Violin and cello are dual-role nodes.",
          why: "Each one listens to the conductor's cue topics and publishes its own instrument topic.",
          concept: "Dual-role nodes are common in ROS because nodes often transform or react to incoming data before publishing new data.",
          mapping: "The musician block combines incoming conductor edges with one outgoing instrument edge, which is exactly the dual-role pattern in the graph.",
        },
      },
      {
        id: "symphony-concurrency",
        eventIndex: 9,
        title: "Do instrument timers have to wait for the conductor?",
        prompt: "The violin plays again before the next conductor cue arrives. Is that a problem?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "no-independent-timers",
            label: "No. The conductor and instruments keep their own timers, and the executor lets those streams interleave",
          },
          {
            id: "yes-cues-first",
            label: "Yes. Every instrument must wait for a fresh conductor cue before it can publish again",
          },
          {
            id: "yes-spotlight-blocks",
            label: "Yes. Spotlight must finish before any instrument timer can fire a second time",
          },
        ],
        correctChoiceId: "no-independent-timers",
        focus: {
          codeBlockIds: ["conductor", "violin", "main-spin"],
          graphElementIds: [
            "node:conductor",
            "topic:tempo",
            "topic:dynamics",
            "node:violin",
            "topic:violin",
            "node:audience",
            "node:spotlight",
          ],
          eventIndices: [1, 4, 9],
        },
        hint: "Compare the 3.0 second conductor timer to the violin timer and remember what main() adds to the executor.",
        successFeedback: "Correct — the streams interleave because their timers are independent.",
        correctionFeedback: "Not quite. The conductor sets cues, but the musicians still keep their own timers and can publish again before the next cue.",
        notice: "Concurrency means one stream can continue moving even while another stream is between callbacks.",
        explanation: {
          what: "The second violin note is normal, not a timing error.",
          why: "The conductor and violin each have their own timers, and MultiThreadedExecutor keeps those callback paths alive together.",
          concept: "Executor-driven concurrency lets separate ROS streams interleave instead of forcing one giant sequence.",
          mapping: "The conductor block shows one timer, the violin block shows a faster timer, and the main-spin block is what keeps both paths running side by side.",
        },
      },
      {
        id: "symphony-violin-fanout",
        eventIndex: 6,
        title: "Find the fan-out point for /violin",
        prompt: "Click the graph element that sends one violin note to both audience and spotlight.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["topic:violin"],
        focus: {
          codeBlockIds: ["violin", "audience", "spotlight"],
          graphElementIds: [
            "topic:violin",
            "edge:sym:violin_to_audience",
            "edge:sym:violin_to_spotlight",
            "node:audience",
            "node:spotlight",
          ],
          eventIndices: [4, 5, 6],
        },
        hint: "Look for the shared transport in the middle, not either listener node.",
        successFeedback: "Yes — /violin is the shared channel that fans one note out to both listeners.",
        correctionFeedback: "Not quite. The branching happens at the topic itself, not inside audience or spotlight.",
        notice: "A single publish call can wake multiple subscribers because the topic is the shared transport.",
        explanation: {
          what: "/violin is the fan-out point for the solo note.",
          why: "Audience and spotlight both subscribe to the same topic, so ROS duplicates the delivery path from there.",
          concept: "Topic fan-out lets different subscribers reuse the same published stream for different jobs.",
          mapping: "The violin publish block sends one note into /violin, and the graph then branches that note toward both audience and spotlight.",
        },
      },
      {
        id: "symphony-flute-composability",
        eventIndex: 11,
        title: "Add a flute section",
        prompt: "If a flute joins the orchestra, what is the smallest clean change to the system?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "add-flute-stream",
            label: "Add a flute node and /flute topic; keep the current players unchanged, and only add an audience subscription if audience should hear flute",
          },
          {
            id: "rewrite-whole-orchestra",
            label: "Rewrite conductor, violin, cello, bass, audience, and spotlight so they all know about flute before anything can run",
          },
          {
            id: "merge-into-one-callback",
            label: "Replace the executor with one giant callback that sequences every instrument by hand",
          },
        ],
        correctChoiceId: "add-flute-stream",
        focus: {
          codeBlockIds: ["conductor", "audience", "main-spin"],
          graphElementIds: [
            "node:conductor",
            "topic:tempo",
            "topic:dynamics",
            "node:violin",
            "topic:violin",
            "node:cello",
            "topic:cello",
            "node:bass",
            "topic:bass",
            "node:audience",
          ],
          eventIndices: [0, 11],
        },
        hint: "Think about adding one more stream without disturbing the streams that already work.",
        successFeedback: "Correct — composability means adding one more node/topic pair instead of rewriting the orchestra.",
        correctionFeedback: "Not quite. This architecture scales by adding another stream, not by rewriting every existing node.",
        notice: "Topics keep the nodes loosely coupled, which is why a new performer can slot into the pattern cleanly.",
        explanation: {
          what: "A flute can join by adding one new node/topic path and an optional audience subscription.",
          why: "The existing performers do not need to know about flute unless they actually exchange data with it.",
          concept: "Composability comes from loosely coupled nodes connected by topics.",
          mapping: "The current graph already shows the reusable pattern: add another performer node, another topic, and only the specific edges that new stream needs.",
        },
      },
      {
        id: "symphony-why-not-one-node",
        eventIndex: 11,
        title: "Why not one giant node?",
        prompt: "Why not put conductor, musicians, audience, and spotlight into one giant callback-heavy node?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "independent-roles",
            label: "Separate nodes keep cue broadcasts, selective subscriptions, and independent timers clear and easy to extend",
          },
          {
            id: "one-topic-limit",
            label: "Because ROS allows only one topic connection per node",
          },
          {
            id: "same-type-limit",
            label: "Because Float32 and String messages cannot exist inside the same node",
          },
        ],
        correctChoiceId: "independent-roles",
        focus: {
          codeBlockIds: ["conductor", "violin", "cello", "bass", "audience", "spotlight", "main-spin"],
          graphElementIds: [
            "node:conductor",
            "topic:tempo",
            "topic:dynamics",
            "node:violin",
            "topic:violin",
            "node:cello",
            "topic:cello",
            "node:bass",
            "topic:bass",
            "node:audience",
            "node:spotlight",
          ],
          eventIndices: [0, 1, 3, 6, 11],
        },
        hint: "Think about role separation, selective wiring, and how easy it is to add or replace one part.",
        successFeedback: "Correct — the lesson is separation of roles, not a ROS rule that forbids big nodes.",
        correctionFeedback: "Not quite. One giant node is possible, but it hides the independence and composability this example is trying to teach.",
        notice: "ROS favors small cooperating nodes because it keeps the system understandable and easier to extend.",
        explanation: {
          what: "Separate nodes make the orchestra's jobs and connections much clearer.",
          why: "Each node can focus on one role while topics connect only the pieces that actually need to exchange data.",
          concept: "Why ROS uses multiple nodes instead of one tangled program.",
          mapping: "The separate code blocks match the separate graph nodes and edges, which is exactly the structure a giant all-in-one callback would blur together.",
        },
      },
    ],
  },
  "distance-aware-rover": {
    templateId: "distance-aware-rover",
    title: "Distance-Aware Rover Walkthrough",
    summary: "Practice how two sensor topics wake different callbacks and how one speed command fans out to two listeners.",
    practiced: ["parallel sensor streams", "two subscriptions", "callback choice", "command fan-out"],
    steps: [
      {
        id: "rover-difference",
        eventIndex: 0,
        title: "How is this different from Simple Publisher?",
        prompt: "Compared with Simple Publisher, what is the biggest new idea in this rover example?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "two-inputs-one-output",
            label: "One controller listens to two sensor topics and sends one command topic to two subscribers",
          },
          {
            id: "timer-drives-motors",
            label: "A timer now sends commands straight to the motor driver with no controller",
          },
          {
            id: "actions-instead-of-topics",
            label: "The example switched from topics to actions",
          },
        ],
        correctChoiceId: "two-inputs-one-output",
        focus: {
          codeBlockIds: ["controller-setup"],
          graphElementIds: [
            "node:front_sensor",
            "node:rear_sensor",
            "node:rover_controller",
            "topic:front_range",
            "topic:rear_range",
            "topic:cmd_vel",
          ],
          eventIndices: [0, 1, 2, 3],
        },
        hint: "Look for what changed beyond one timer and one topic. The controller now has more than one input and more than one downstream listener.",
        successFeedback: "Correct — this example adds parallel sensor inputs, separate callbacks, and a fan-out command topic.",
        correctionFeedback: "Not quite. The key jump from Simple Publisher is that one node now reacts to two incoming topics and then fans one command out to two listeners.",
        notice: "How is this different from Simple Publisher? That example had one timer callback and one outgoing topic. This rover has two input streams, two controller callbacks, and one command topic that reaches two subscribers.",
        explanation: {
          what: "This example teaches a controller node that reacts to more than one input stream.",
          why: "Real robot behavior often depends on several sensors instead of one straight publish path.",
          concept: "Parallel sensor streams and callback-driven control.",
          mapping: "The graph shows two topics entering rover_controller, and the controller-setup block shows two create_subscription(...) calls plus one create_publisher(...).",
        },
      },
      {
        id: "rover-front-sensor",
        eventIndex: 1,
        title: "Find the front sensor",
        prompt: "Click the graph node that publishes the front distance reading.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["node:front_sensor"],
        focus: {
          codeBlockIds: ["front-sensor-setup"],
          graphElementIds: ["node:front_sensor", "topic:front_range", "edge:rover:front_sensor_to_front_range"],
          eventIndices: [1],
        },
        hint: "It is the upper-left node connected to /front_range.",
        successFeedback: "Yes — front_sensor is the publisher for the front distance stream.",
        correctionFeedback: "Not quite. Look for the upper-left node that feeds /front_range.",
        notice: "The two left-side nodes are separate publishers. Start by locating the one that watches the front wall.",
        explanation: {
          what: "front_sensor is the node that turns front distance measurements into ROS messages.",
          why: "It owns the timer callback that publishes onto /front_range.",
          concept: "A sensor node can publish its own topic without waiting for the rest of the system.",
          mapping: "The front-sensor-setup block creates the publisher and timer, and the graph shows its outgoing path into /front_range.",
        },
      },
      {
        id: "rover-rear-sensor",
        eventIndex: 1,
        title: "Find the rear sensor",
        prompt: "Click the graph node that publishes the rear distance reading.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["node:rear_sensor"],
        focus: {
          codeBlockIds: ["rear-sensor-setup"],
          graphElementIds: ["node:rear_sensor", "topic:rear_range", "edge:rover:rear_sensor_to_rear_range"],
          eventIndices: [1],
        },
        hint: "It is the lower-left node connected to /rear_range.",
        successFeedback: "Correct — rear_sensor is the second independent publisher.",
        correctionFeedback: "Close. Choose the lower-left node that feeds /rear_range.",
        notice: "The rear sensor repeats the same publishing pattern on its own topic, which is what makes the example parallel instead of one-directional.",
        explanation: {
          what: "rear_sensor publishes the back-wall distance on /rear_range.",
          why: "The rover needs a second input stream so it can react when backing up gets unsafe.",
          concept: "A second publisher creates a second source of runtime events.",
          mapping: "The rear-sensor-setup block mirrors the front sensor pattern, and the graph shows its own separate topic path.",
        },
      },
      {
        id: "rover-controller-subscriptions",
        eventIndex: 0,
        title: "Find both subscriptions",
        prompt: "Click the code block where rover_controller subscribes to both sensor topics.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["controller-setup"],
        focus: {
          codeBlockIds: ["controller-setup"],
          graphElementIds: [
            "node:rover_controller",
            "topic:front_range",
            "topic:rear_range",
            "topic:cmd_vel",
            "edge:rover:front_range_to_controller",
            "edge:rover:rear_range_to_controller",
            "edge:rover:controller_to_cmd_vel",
          ],
          eventIndices: [0, 2, 8],
        },
        hint: "Look for the block with two create_subscription(...) calls and one create_publisher(...).",
        successFeedback: "Yes — this block is where one node listens to both sensor topics.",
        correctionFeedback: "Not quite. Find the setup block where rover_controller creates two subscriptions.",
        notice: "This is the heart of the example: one node has two incoming topic connections, so different messages can wake different callbacks.",
        explanation: {
          what: "rover_controller subscribes to both /front_range and /rear_range, then publishes commands on /cmd_vel.",
          why: "The controller needs both inputs so it can decide whether to go forward or reverse.",
          concept: "Multi-topic subscription inside one node.",
          mapping: "The two create_subscription(...) lines match the two curved incoming edges in the graph, and create_publisher(...) matches the outgoing /cmd_vel edge.",
        },
      },
      {
        id: "rover-predict-front-callback",
        eventIndex: 1,
        title: "Predict which callback runs",
        prompt: "After the front sensor publishes on /front_range, which callback should run next?",
        questionType: "predict_next",
        choices: [
          { id: "front-callback", label: "front_range_callback()" },
          { id: "rear-callback", label: "rear_range_callback()" },
          { id: "drive-callback", label: "drive_callback()" },
        ],
        correctChoiceId: "front-callback",
        focus: {
          codeBlockIds: ["front-callback", "controller-setup"],
          graphElementIds: ["topic:front_range", "edge:rover:front_range_to_controller", "node:rover_controller"],
          eventIndices: [1, 2],
        },
        hint: "Follow the topic name. The callback name matches the topic that woke it.",
        successFeedback: "Correct — /front_range wakes front_range_callback().",
        correctionFeedback: "Not quite. The controller has one callback per sensor topic, so /front_range wakes the front callback.",
        notice: "Separate subscriptions mean ROS does not run every callback at once. It runs the one connected to the topic that just received a message.",
        explanation: {
          what: "front_range_callback() is the next major step after a /front_range message arrives.",
          why: "That is the callback that create_subscription(...) registered for the front topic.",
          concept: "Topic-to-callback mapping.",
          mapping: "The front topic edge into rover_controller matches the front-callback block in code.",
        },
      },
      {
        id: "rover-front-path",
        eventIndex: 2,
        title: "Trace the front callback path",
        prompt: "Click the graph edge that carries the front sensor reading into rover_controller.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:rover:front_range_to_controller"],
        focus: {
          codeBlockIds: ["front-callback"],
          graphElementIds: ["edge:rover:front_range_to_controller", "topic:front_range", "node:rover_controller"],
          eventIndices: [2],
        },
        hint: "It is the upper curved edge that ends at rover_controller.",
        successFeedback: "Yes — that edge is the front subscription path.",
        correctionFeedback: "Close. Choose the curved edge from /front_range into rover_controller.",
        notice: "The graph lets you see which input stream is waking the controller at this moment.",
        explanation: {
          what: "That edge represents the front distance message reaching the controller.",
          why: "The controller cannot make a decision until a sensor topic delivers a message into one of its subscriptions.",
          concept: "Subscription delivery path.",
          mapping: "The front_range_callback() code block is the code-side view of this front subscription edge.",
        },
      },
      {
        id: "rover-fan-out",
        eventIndex: 3,
        title: "Find the fan-out point",
        prompt: "Click the graph element that splits the drive command to both the motor driver and the logger.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["topic:cmd_vel"],
        focus: {
          codeBlockIds: ["front-callback", "motor-driver"],
          graphElementIds: [
            "topic:cmd_vel",
            "edge:rover:cmd_vel_to_motor_driver",
            "edge:rover:cmd_vel_to_logger",
            "node:motor_driver",
            "node:logger",
          ],
          eventIndices: [3, 6],
        },
        hint: "Look for the shared topic between rover_controller and the two right-side nodes.",
        successFeedback: "Correct — /cmd_vel is the shared channel that fans the command out to both subscribers.",
        correctionFeedback: "Not quite. The split happens at the topic itself, not inside either subscriber node.",
        notice: "One publish call can reach several listeners because the topic is the shared transport channel.",
        explanation: {
          what: "/cmd_vel is the point where one command becomes two deliveries.",
          why: "Both motor_driver and logger subscribe to the same topic.",
          concept: "Topic fan-out.",
          mapping: "The controller publishes once in code, and the graph then shows two outgoing subscriber edges from /cmd_vel.",
        },
      },
      {
        id: "rover-composability",
        eventIndex: 3,
        title: "What if you needed a side sensor?",
        prompt: "If the rover needed to detect obstacles to the left, what would you add to this system?",
        questionType: "multiple_choice",
        choices: [
          {
            id: "add-side-sensor",
            label: "A new SideSensor node, a /side_range topic, and a new subscription in rover_controller",
          },
          {
            id: "modify-front-sensor",
            label: "Modify front_sensor to also look sideways",
          },
          {
            id: "motor-driver-parameter",
            label: "Add a parameter to motor_driver to check the side",
          },
        ],
        correctChoiceId: "add-side-sensor",
        focus: {
          codeBlockIds: ["controller-setup"],
          graphElementIds: [
            "node:front_sensor",
            "node:rear_sensor",
            "node:rover_controller",
            "node:motor_driver",
            "node:logger",
            "topic:front_range",
            "topic:rear_range",
            "topic:cmd_vel",
          ],
          eventIndices: [0, 3, 6, 7],
        },
        hint: "ROS grows by plugging in another node and topic path, not by stuffing new jobs into whichever node already exists.",
        successFeedback: "Correct — ROS composability means adding a new sensor node, a new topic, and one more subscription path.",
        correctionFeedback: "Not quite. The clean ROS answer is to add a new node and topic, then subscribe to that topic where the decision is made.",
        notice: "The current graph already shows the pattern: sensors publish their own topics, rover_controller listens, and listeners on /cmd_vel stay separate.",
        explanation: {
          what: "A side obstacle would fit the same pattern as the front and rear sensors: its own node, its own topic, and one more subscription in the controller.",
          why: "The controller is where sensor inputs are combined into drive decisions, while motor_driver and logger keep their own focused jobs.",
          concept: "ROS lets you add components by plugging in new nodes and topics. The existing sensors, controller callbacks, and listeners don't need to change. This is what makes ROS systems composable.",
          mapping: "The highlighted topology shows the reusable structure already in place: sensor nodes publish topics, rover_controller subscribes, and the command topic still fans out to its listeners.",
        },
      },
      {
        id: "rover-reverse-why",
        eventIndex: 5,
        title: "Why does it reverse?",
        prompt: "Why does the same front callback send reverse motion later in the sequence?",
        questionType: "multiple_choice",
        choices: [
          { id: "front-too-close", label: "The new front reading is below the stop threshold" },
          { id: "rear-topic-fired", label: "The rear topic secretly woke the front callback" },
          { id: "logger-changed-cmd", label: "The logger changed the command after the controller published" },
        ],
        correctChoiceId: "front-too-close",
        focus: {
          codeBlockIds: ["front-callback"],
          graphElementIds: ["topic:front_range", "edge:rover:front_range_to_controller", "node:rover_controller"],
          eventIndices: [4, 5, 6],
        },
        hint: "The code block did not change. The incoming distance value did.",
        successFeedback: "Yes — the same callback makes a different choice because the front distance crossed the threshold.",
        correctionFeedback: "Not quite. The front callback reverses because the new front reading is too small, not because another node changed the path.",
        notice: "Event-driven control is about reacting to new data. The callback stays the same while the message value changes.",
        explanation: {
          what: "front_range_callback() reverses because the front reading is now below front_stop_distance.",
          why: "The conditional line picks -0.2 m/s when the front wall is too close.",
          concept: "The same callback can produce a different action when the input data changes.",
          mapping: "The code branch in front-callback matches the switch from the clear-path event to the obstacle event in the graph timeline.",
        },
      },
      {
        id: "rover-predict-rear-callback",
        eventIndex: 7,
        title: "Predict the rear reaction",
        prompt: "After the rear sensor reports a wall close behind the rover, what major step should happen next?",
        questionType: "predict_next",
        choices: [
          { id: "rear-callback-forward", label: "rear_range_callback() runs and sends the rover forward" },
          { id: "front-callback-reverse", label: "front_range_callback() runs again and keeps reversing" },
          { id: "motor-driver-publishes", label: "motor_driver publishes a new range topic" },
        ],
        correctChoiceId: "rear-callback-forward",
        focus: {
          codeBlockIds: ["rear-callback", "controller-setup"],
          graphElementIds: ["topic:rear_range", "edge:rover:rear_range_to_controller", "node:rover_controller"],
          eventIndices: [7, 8],
        },
        hint: "Follow the rear topic into rover_controller. A different subscription means a different callback.",
        successFeedback: "Correct — the rear callback wakes up and pushes the rover forward away from the back wall.",
        correctionFeedback: "Not quite. A /rear_range message wakes the rear callback, not the front one.",
        notice: "The controller has two separate callback paths, so the rear sensor can take control when backing up is no longer safe.",
        explanation: {
          what: "The next major step is rear_range_callback() running and changing the rover back to forward motion.",
          why: "The rear reading fell below rear_stop_distance, so the rear callback publishes a forward command.",
          concept: "Different input topics can trigger different recovery behaviors inside the same node.",
          mapping: "The rear subscription edge in the graph lines up with the rear-callback block in code and with the final forward-again timeline step.",
        },
      },
    ],
  },
  "dock-action-client": {
    templateId: "dock-action-client",
    title: "Dock Action Client Walkthrough",
    summary: "Practice how action setup, goal sending, feedback, and result callbacks map between code and the graph.",
    practiced: ["action client setup", "goal sending", "feedback callback", "result flow"],
    steps: [
      {
        id: "action-client-setup-block",
        eventIndex: 0,
        title: "Find the action client setup",
        prompt: "Click the code block that creates the ActionClient connected to /dock.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["action-client-setup"],
        focus: {
          codeBlockIds: ["action-client-setup"],
          graphElementIds: ["node:dock_action_client", "action:dock_server", "edge:action:goal"],
          eventIndices: [0],
        },
        hint: "It is in __init__(), where the client is created before any goal is sent.",
        successFeedback: "Yes — this block creates the client-side connection to the Dock action server.",
        correctionFeedback: "Not quite. Look for the block with ActionClient(self, Dock, \"dock\").",
        notice: "This setup is what makes the client-to-server action relationship appear in the graph.",
        explanation: {
          what: "The node constructs an ActionClient for the dock action.",
          why: "The action client must exist before it can send goals or receive callbacks.",
          concept: "Action client setup.",
          mapping: "The ActionClient(...) line corresponds to the client node being linked to the /dock action server.",
        },
      },
      {
        id: "send-goal-block",
        eventIndex: 1,
        title: "Find the goal-sending code",
        prompt: "Click the code block that builds the goal and sends it asynchronously.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["send-goal"],
        focus: {
          codeBlockIds: ["send-goal"],
          graphElementIds: ["node:dock_action_client", "edge:action:goal", "action:dock_server"],
          eventIndices: [1],
        },
        hint: "Look for Dock.Goal(), wait_for_server(), and send_goal_async(...).",
        successFeedback: "Correct — this block creates the goal and sends it to the action server.",
        correctionFeedback: "Close. Find the method that calls send_goal_async(...).",
        notice: "Action clients send goals asynchronously rather than blocking until the result is ready.",
        explanation: {
          what: "send_goal() builds the goal and hands it to send_goal_async(...).",
          why: "Actions are asynchronous, so the client sends the request and then waits through callbacks.",
          concept: "Asynchronous action goal sending.",
          mapping: "This code block maps to the goal lane that travels from the client node to the action server.",
        },
      },
      {
        id: "goal-lane-graph",
        eventIndex: 1,
        title: "Trace the goal lane",
        prompt: "Click the graph lane that carries the docking goal from the client to the action server.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:action:goal"],
        focus: {
          codeBlockIds: ["send-goal"],
          graphElementIds: ["edge:action:goal", "node:dock_action_client", "action:dock_server"],
          eventIndices: [1],
        },
        hint: "It is the outgoing path from the client toward /dock before any feedback comes back.",
        successFeedback: "Yes — that lane is the outbound goal request.",
        correctionFeedback: "Not quite. Choose the path from the client to the server, not one of the return paths.",
        notice: "Goal, feedback, and result each use their own conceptual lane in this teaching diagram.",
        explanation: {
          what: "The goal lane represents the request moving from the action client to the server.",
          why: "The action server must receive a goal before it can accept it or send feedback.",
          concept: "Outbound action goal flow.",
          mapping: "The send_goal_async(...) call in code corresponds to this directed graph lane.",
        },
      },
      {
        id: "feedback-callback-choice",
        eventIndex: 3,
        title: "Choose the feedback callback",
        prompt: "Which callback handles intermediate feedback while docking is still in progress?",
        questionType: "multiple_choice",
        choices: [
          { id: "feedback-callback", label: "feedback_callback()" },
          { id: "goal-response", label: "goal_response_callback()" },
          { id: "get-result", label: "get_result_callback()" },
        ],
        correctChoiceId: "feedback-callback",
        focus: {
          codeBlockIds: ["feedback-callback"],
          graphElementIds: ["edge:action:feedback", "node:dock_action_client", "action:dock_server"],
          eventIndices: [3],
        },
        hint: "This callback reacts to progress updates before the final result arrives.",
        successFeedback: "Correct — feedback_callback() handles the intermediate feedback stream.",
        correctionFeedback: "Not quite. Goal response and result are different stages from ongoing feedback.",
        notice: "Feedback is the mid-action progress channel, not the final answer.",
        explanation: {
          what: "feedback_callback() receives progress updates while the action is still running.",
          why: "Actions can stream intermediate status back before they finish.",
          concept: "Action feedback callbacks.",
          mapping: "The feedback lane in the graph corresponds to feedback_callback() in code.",
        },
      },
      {
        id: "predict-feedback-next",
        eventIndex: 2,
        title: "Predict the next action stage",
        prompt: "After the goal is accepted, what major stage usually happens next in this example?",
        questionType: "predict_next",
        choices: [
          { id: "feedback", label: "The server sends feedback updates" },
          { id: "result", label: "The final result arrives immediately" },
          { id: "setup", label: "The action client is created again" },
        ],
        correctChoiceId: "feedback",
        focus: {
          codeBlockIds: ["goal-response", "feedback-callback"],
          graphElementIds: ["edge:action:feedback", "edge:action:result", "action:dock_server"],
          eventIndices: [2, 3],
        },
        hint: "The client usually receives progress information before the action is finished.",
        successFeedback: "Yes — feedback typically arrives after acceptance and before the final result.",
        correctionFeedback: "Close. The action server usually reports progress before sending the final result.",
        notice: "Actions separate acceptance, feedback, and final result into different stages.",
        explanation: {
          what: "The next major stage is feedback arriving while the dock behavior is still executing.",
          why: "The server can stream progress before completion.",
          concept: "Action sequencing: goal acceptance, feedback, then result.",
          mapping: "goal_response_callback() sets up the waiting, and feedback_callback() handles the next visible runtime step.",
        },
      },
      {
        id: "result-lane-graph",
        eventIndex: 4,
        title: "Trace the final result",
        prompt: "When docking finishes, click the graph lane that brings the final result back to the client.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:action:result"],
        focus: {
          codeBlockIds: ["get-result"],
          graphElementIds: ["edge:action:result", "action:dock_server", "node:dock_action_client"],
          eventIndices: [4],
        },
        hint: "It is the return path used after the action is complete, not while it is still progressing.",
        successFeedback: "Correct — that lane represents the final result coming back to the client.",
        correctionFeedback: "Not quite. Choose the return path for completion, not the feedback lane.",
        notice: "Results close out the action after the server has finished the behavior.",
        explanation: {
          what: "The result lane carries the final docking outcome back to the client.",
          why: "Once the action completes, the result callback receives the final status.",
          concept: "Action result handling.",
          mapping: "The graph’s result lane corresponds to get_result_callback() reading future.result().result in code.",
        },
      },
    ],
  },
};

export function getGuidedLesson(templateId) {
  return GUIDED_LESSONS[templateId] || null;
}
