export const GUIDED_LESSONS = {
  "simple-publisher": {
    templateId: "simple-publisher",
    title: "Simple Publisher Walkthrough",
    summary: "Practice how a timer callback maps to code, publish flow, and topic fan-out.",
    practiced: ["publisher setup", "timer callback", "publish path", "topic fan-out"],
    steps: [
      {
        id: "publisher-setup-block",
        eventIndex: 0,
        title: "Find the publisher setup",
        prompt: "Click the code block that creates the publisher and registers the timer callback.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["publisher-setup"],
        focus: {
          codeBlockIds: ["publisher-setup"],
          graphElementIds: ["node:simple_publisher", "topic:my_publisher", "edge:pub:publisher_to_topic"],
          eventIndices: [0],
        },
        hint: "Look inside __init__(). The publisher is created before the timer ever fires.",
        successFeedback: "Yes — this block creates the publisher and the timer.",
        correctionFeedback: "Not quite. Look for the constructor block where create_publisher(...) appears.",
        notice: "This is the setup step that makes the publisher-to-topic connection exist at runtime.",
        explanation: {
          what: "The constructor creates the node, publisher, and timer.",
          why: "ROS needs the publisher and timer objects before any callback can run.",
          concept: "Node setup and publisher creation.",
          mapping: "The __init__ block maps directly to the publisher node and topic relationship in the graph.",
        },
      },
      {
        id: "timer-callback-block",
        eventIndex: 1,
        title: "Find the timer callback",
        prompt: "Click the code block that runs when the timer expires.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["timer-callback"],
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: ["node:simple_publisher"],
          eventIndices: [1],
        },
        hint: "Look for the function that is named in create_timer(..., self.timer_callback).",
        successFeedback: "Correct — this callback is what the timer triggers.",
        correctionFeedback: "Close. Look for the callback function the timer calls, not the constructor.",
        notice: "The timer causes this callback to run before any message can be published.",
        explanation: {
          what: "timer_callback() is the function ROS invokes when the timer period elapses.",
          why: "create_timer(...) registered this callback during setup.",
          concept: "Timer-driven execution.",
          mapping: "The active node in the graph is waiting for the timer, and this callback is the code side of that event.",
        },
      },
      {
        id: "publish-path-graph",
        eventIndex: 3,
        title: "Trace the publish path",
        prompt: "Click the graph path that carries the message from the publisher node into the topic.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:pub:publisher_to_topic"],
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: ["edge:pub:publisher_to_topic", "node:simple_publisher", "topic:my_publisher"],
          eventIndices: [3],
        },
        hint: "It is the first edge the message takes before subscribers see anything.",
        successFeedback: "Yes — that edge represents publish(msg) moving data onto the topic.",
        correctionFeedback: "Not quite. Start at the publisher node and find the first outgoing message path.",
        notice: "A publish call reaches the topic first, then ROS can fan the data out to subscribers.",
        explanation: {
          what: "publish(msg) sends the message from the node into the topic transport.",
          why: "Topics act as the communication channel between publishers and subscribers.",
          concept: "Topic publish flow.",
          mapping: "The publish(msg) line in timer_callback() corresponds to this first graph edge.",
        },
      },
      {
        id: "predict-message-created",
        eventIndex: 1,
        title: "Predict the next step",
        prompt: "After the timer fires, what is the next major step in this example?",
        questionType: "predict_next",
        choices: [
          { id: "message-created", label: "Create and fill a String message" },
          { id: "spin-loop", label: "Return immediately to spin()" },
          { id: "subscriber-update", label: "Subscribers receive the message first" },
        ],
        correctChoiceId: "message-created",
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: ["node:simple_publisher"],
          eventIndices: [1, 2],
        },
        hint: "The callback needs data to publish before the topic can change.",
        successFeedback: "Correct — the callback builds the message before publish(msg) runs.",
        correctionFeedback: "Close. The node prepares the message object before anything moves through the graph.",
        notice: "The code sequence is timer callback, message creation, then publish.",
        explanation: {
          what: "The next step is creating and filling the String message object.",
          why: "ROS cannot publish until the code has prepared a message payload.",
          concept: "Execution order inside a callback.",
          mapping: "In code, msg = String() and msg.data = ... happen before the graph shows any message movement.",
        },
      },
      {
        id: "topic-fan-out",
        eventIndex: 3,
        title: "Find the fan-out point",
        prompt: "Click the graph element that fans the published message out to both subscribers.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["topic:my_publisher"],
        focus: {
          codeBlockIds: ["timer-callback"],
          graphElementIds: [
            "topic:my_publisher",
            "edge:pub:topic_to_listener",
            "edge:pub:topic_to_dashboard",
            "node:string_listener",
            "node:string_dashboard",
          ],
          eventIndices: [3],
        },
        hint: "Look for the center channel between the publisher and both subscribers.",
        successFeedback: "Yes — the topic is the shared channel that branches to both subscribers.",
        correctionFeedback: "Not quite. The fan-out happens at the topic itself, not inside either subscriber node.",
        notice: "A single publish call can reach multiple subscribers because the topic is the shared transport.",
        explanation: {
          what: "The topic is the shared communication point that distributes the message to every subscriber.",
          why: "Subscribers listen to the topic rather than to the publisher directly.",
          concept: "Publish/subscribe fan-out.",
          mapping: "One publish(msg) call in code causes the graph to branch from the topic to each subscriber edge.",
        },
      },
    ],
  },
  "dock-action-client": {
    templateId: "dock-action-client",
    title: "Dock Action Client Walkthrough",
    summary: "Practice how action setup, goal sending, feedback, and result callbacks map between code and the graph.",
    practiced: ["action client setup", "goal sending", "feedback callback", "result flow"],
    steps: [
      {
        id: "action-client-setup-block",
        eventIndex: 0,
        title: "Find the action client setup",
        prompt: "Click the code block that creates the ActionClient connected to /dock.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["action-client-setup"],
        focus: {
          codeBlockIds: ["action-client-setup"],
          graphElementIds: ["node:dock_action_client", "action:dock_server", "edge:action:goal"],
          eventIndices: [0],
        },
        hint: "It is in __init__(), where the client is created before any goal is sent.",
        successFeedback: "Yes — this block creates the client-side connection to the Dock action server.",
        correctionFeedback: "Not quite. Look for the block with ActionClient(self, Dock, \"dock\").",
        notice: "This setup is what makes the client-to-server action relationship appear in the graph.",
        explanation: {
          what: "The node constructs an ActionClient for the dock action.",
          why: "The action client must exist before it can send goals or receive callbacks.",
          concept: "Action client setup.",
          mapping: "The ActionClient(...) line corresponds to the client node being linked to the /dock action server.",
        },
      },
      {
        id: "send-goal-block",
        eventIndex: 1,
        title: "Find the goal-sending code",
        prompt: "Click the code block that builds the goal and sends it asynchronously.",
        questionType: "click_code_block",
        acceptableCodeBlockIds: ["send-goal"],
        focus: {
          codeBlockIds: ["send-goal"],
          graphElementIds: ["node:dock_action_client", "edge:action:goal", "action:dock_server"],
          eventIndices: [1],
        },
        hint: "Look for Dock.Goal(), wait_for_server(), and send_goal_async(...).",
        successFeedback: "Correct — this block creates the goal and sends it to the action server.",
        correctionFeedback: "Close. Find the method that calls send_goal_async(...).",
        notice: "Action clients send goals asynchronously rather than blocking until the result is ready.",
        explanation: {
          what: "send_goal() builds the goal and hands it to send_goal_async(...).",
          why: "Actions are asynchronous, so the client sends the request and then waits through callbacks.",
          concept: "Asynchronous action goal sending.",
          mapping: "This code block maps to the goal lane that travels from the client node to the action server.",
        },
      },
      {
        id: "goal-lane-graph",
        eventIndex: 1,
        title: "Trace the goal lane",
        prompt: "Click the graph lane that carries the docking goal from the client to the action server.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:action:goal"],
        focus: {
          codeBlockIds: ["send-goal"],
          graphElementIds: ["edge:action:goal", "node:dock_action_client", "action:dock_server"],
          eventIndices: [1],
        },
        hint: "It is the outgoing path from the client toward /dock before any feedback comes back.",
        successFeedback: "Yes — that lane is the outbound goal request.",
        correctionFeedback: "Not quite. Choose the path from the client to the server, not one of the return paths.",
        notice: "Goal, feedback, and result each use their own conceptual lane in this teaching diagram.",
        explanation: {
          what: "The goal lane represents the request moving from the action client to the server.",
          why: "The action server must receive a goal before it can accept it or send feedback.",
          concept: "Outbound action goal flow.",
          mapping: "The send_goal_async(...) call in code corresponds to this directed graph lane.",
        },
      },
      {
        id: "feedback-callback-choice",
        eventIndex: 3,
        title: "Choose the feedback callback",
        prompt: "Which callback handles intermediate feedback while docking is still in progress?",
        questionType: "multiple_choice",
        choices: [
          { id: "feedback-callback", label: "feedback_callback()" },
          { id: "goal-response", label: "goal_response_callback()" },
          { id: "get-result", label: "get_result_callback()" },
        ],
        correctChoiceId: "feedback-callback",
        focus: {
          codeBlockIds: ["feedback-callback"],
          graphElementIds: ["edge:action:feedback", "node:dock_action_client", "action:dock_server"],
          eventIndices: [3],
        },
        hint: "This callback reacts to progress updates before the final result arrives.",
        successFeedback: "Correct — feedback_callback() handles the intermediate feedback stream.",
        correctionFeedback: "Not quite. Goal response and result are different stages from ongoing feedback.",
        notice: "Feedback is the mid-action progress channel, not the final answer.",
        explanation: {
          what: "feedback_callback() receives progress updates while the action is still running.",
          why: "Actions can stream intermediate status back before they finish.",
          concept: "Action feedback callbacks.",
          mapping: "The feedback lane in the graph corresponds to feedback_callback() in code.",
        },
      },
      {
        id: "predict-feedback-next",
        eventIndex: 2,
        title: "Predict the next action stage",
        prompt: "After the goal is accepted, what major stage usually happens next in this example?",
        questionType: "predict_next",
        choices: [
          { id: "feedback", label: "The server sends feedback updates" },
          { id: "result", label: "The final result arrives immediately" },
          { id: "setup", label: "The action client is created again" },
        ],
        correctChoiceId: "feedback",
        focus: {
          codeBlockIds: ["goal-response", "feedback-callback"],
          graphElementIds: ["edge:action:feedback", "edge:action:result", "action:dock_server"],
          eventIndices: [2, 3],
        },
        hint: "The client usually receives progress information before the action is finished.",
        successFeedback: "Yes — feedback typically arrives after acceptance and before the final result.",
        correctionFeedback: "Close. The action server usually reports progress before sending the final result.",
        notice: "Actions separate acceptance, feedback, and final result into different stages.",
        explanation: {
          what: "The next major stage is feedback arriving while the dock behavior is still executing.",
          why: "The server can stream progress before completion.",
          concept: "Action sequencing: goal acceptance, feedback, then result.",
          mapping: "goal_response_callback() sets up the waiting, and feedback_callback() handles the next visible runtime step.",
        },
      },
      {
        id: "result-lane-graph",
        eventIndex: 4,
        title: "Trace the final result",
        prompt: "When docking finishes, click the graph lane that brings the final result back to the client.",
        questionType: "click_graph_element",
        acceptableGraphElementIds: ["edge:action:result"],
        focus: {
          codeBlockIds: ["get-result"],
          graphElementIds: ["edge:action:result", "action:dock_server", "node:dock_action_client"],
          eventIndices: [4],
        },
        hint: "It is the return path used after the action is complete, not while it is still progressing.",
        successFeedback: "Correct — that lane represents the final result coming back to the client.",
        correctionFeedback: "Not quite. Choose the return path for completion, not the feedback lane.",
        notice: "Results close out the action after the server has finished the behavior.",
        explanation: {
          what: "The result lane carries the final docking outcome back to the client.",
          why: "Once the action completes, the result callback receives the final status.",
          concept: "Action result handling.",
          mapping: "The graph’s result lane corresponds to get_result_callback() reading future.result().result in code.",
        },
      },
    ],
  },
};

export function getGuidedLesson(templateId) {
  return GUIDED_LESSONS[templateId] || null;
}
